[versions]
antlr = "4.9.2"
kotlin = "2.0.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.10" }

[libraries]
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
